In [1]:
import pandas as pd 
import numpy as np 
from sklearn import linear_model
import matplotlib.pyplot as plt 


In [30]:
df = pd.read_csv(r"C:/Users/Admin/Desktop/JN/Housing.csv")
df.head(2)

price  area  bedrooms  bathrooms  stories  ... hotwaterheating airconditioning parking prefarea furnishingstatus
0  13300000  7420         4          2        3  ...              no             yes       2      yes        furnished
1  12250000  8960         4          4        4  ...              no             yes       3       no        furnished

[2 rows x 13 columns]

In [31]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [32]:
df.describe

<bound method NDFrame.describe of         price  area  bedrooms  bathrooms  stories  ... hotwaterheating airconditioning parking prefarea furnishingstatus
0    13300000  7420         4          2        3  ...              no             yes       2      yes        furnished
1    12250000  8960         4          4        4  ...              no             yes       3       no        furnished
2    12250000  9960         3          2        2  ...              no              no       2      yes   semi-furnished
3    12215000  7500         4          2        2  ...              no             yes       3      yes        furnished
4    11410000  7420         4          1        2  ...              no             yes       2       no        furnished
..        ...   ...       ...        ...      ...  ...             ...             ...     ...      ...              ...
540   1820000  3000         2          1        1  ...              no              no       2       no      unfurnishe

In [33]:
df.shape

(545, 13)

In [34]:
df.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [35]:
df1 = df.drop(['bathrooms','stories','prefarea','guestroom','hotwaterheating','basement','airconditioning','parking'],axis='columns')
df1.head(2)

price  area  bedrooms mainroad furnishingstatus
0  13300000  7420         4      yes        furnished
1  12250000  8960         4      yes        furnished

In [36]:
df['furnishingstatus'].unique()

array(['furnished', 'semi-furnished', 'unfurnished'], dtype=object)

In [37]:
df['mainroad'].unique()

array(['yes', 'no'], dtype=object)

In [38]:
df['bedrooms'].unique()

array([4, 3, 5, 2, 6, 1])

In [39]:
def chk(x):
    if x == 'furnished':
        return 1
    elif x =='semi-furnished':
        return 2
    else:
        return 3

In [40]:
df1['furnished'] = df1['furnishingstatus'].apply(chk)

In [41]:
df1.head(2)

price  area  bedrooms mainroad furnishingstatus  furnished
0  13300000  7420         4      yes        furnished          1
1  12250000  8960         4      yes        furnished          1

In [42]:
df1 = df1.drop('furnishingstatus',axis='columns')

In [43]:
df1.head(2)

price  area  bedrooms mainroad  furnished
0  13300000  7420         4      yes          1
1  12250000  8960         4      yes          1

In [44]:
def chk1(x):
    if x == 'yes':
        return 1
    else:
        return 2
df1['main_road'] = df1['mainroad'].apply(chk1)        

In [45]:
df1.head(2)

price  area  bedrooms mainroad  furnished  main_road
0  13300000  7420         4      yes          1          1
1  12250000  8960         4      yes          1          1

In [46]:
df1 = df1.drop('mainroad',axis='columns')

In [47]:
df1.head(2)

price  area  bedrooms  furnished  main_road
0  13300000  7420         4          1          1
1  12250000  8960         4          1          1

In [48]:
df1['furnished'].unique()

array([1, 2, 3])

In [49]:
df1['main_road'].unique()

array([1, 2])

In [52]:
df1['area'].describe()

count      545.000000
mean      5150.541284
std       2170.141023
min       1650.000000
25%       3600.000000
50%       4600.000000
75%       6360.000000
max      16200.000000
Name: area, dtype: float64

In [54]:
X = df1.drop('price',axis='columns')
X.head(2)

area  bedrooms  furnished  main_road
0  7420         4          1          1
1  8960         4          1          1

In [55]:
y = df1.price
y.head(2)

0    13300000
1    12250000
Name: price, dtype: int64

In [56]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=10)

In [57]:
from sklearn.linear_model import LinearRegression
lrm = LinearRegression() 
lrm.fit(X_train,y_train)
lrm.score(X_test,y_test)

0.41454950479703434

In [58]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
cv = ShuffleSplit(n_splits=5 , test_size=0.2 , random_state=0)
cross_val_score(LinearRegression(),X,y,cv=cv)


array([0.37557178, 0.41665383, 0.41068843, 0.27682371, 0.39243393])